#!/bin/bash
#SBATCH --job-name=pipelinetest
#SBATCH --output=pipelinetest%j.out
#SBATCH --error=pipelinetest%j.err
#SBATCH --time=36:00:00
#SBATCH --partition=broadwl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=20000

#source $WFIRST_ROOT/BYOSED_dev/SNANA_byotest.sourceme
source activate salt3_local
alias python=python3
echo "python:"
which python
echo "python3:"
which python3
#export MY_SALT3_DIR=/home/midai/salt3_local
export PYTHONUNBUFFERED=1

runpipe -c pipeline_training_notrain-wl.txt --mypipe mypipe_notraining.py --batch_mode 0 --randseed 78879 --num 301
