#!/bin/bash
#SBATCH --job-name=pipelinetest
#SBATCH --output=pipelinetest%j.out
#SBATCH --error=pipelinetest%j.err
#SBATCH --time=2:00:00
#SBATCH --partition=broadwl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=8000

source $WFIRST_ROOT/BYOSED_dev/SNANA_byotest.sourceme
source activate salt3
MY_SALT3_DIR=/home/midai/salt3_local

