#!/bin/bash
#SBATCH --job-name=pipelinetest
#SBATCH --output=pipelinetest.out
#SBATCH --error=pipelinetest.err
#SBATCH --time=1:00:00
#SBATCH --partition=broadwl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=2000

python /home/midai/salt3_local/SALT3/salt3/pipeline/runpipe.py -c sampleinput.txt --mypipe 1 --batch_mode 0 --randseed 91225 --num 2
