#!/usr/bin/env python

from saltshaker.training.TrainSALT import RunTraining
import sys, argparse, configparser, os
from saltshaker.config import config_rootdir,loggerconfig

if sys.version_info < (3,0):
    sys.exit('Sorry, Python 2 is not supported')

rt = RunTraining()
rt.main()

